version: "3.1"

services:

  deleteme_db:
    container_name: database_dm
    restart: always
    image: postgres
   
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DB=deleteme
      - POSTGRES_USER=pashkan
      - POSTGRES_PASSWORD=123456
    ports:
      - 5439:5439
    restart: always
    networks: 
      - deleteme_botnet

  web:
    container_name: dweb
    build: .
    command: python app.py
    ports:
      - 8200:8200
    restart: always
    volumes:
      - .:/src
    networks: 
      - deleteme_botnet
    depends_on:
      - deleteme_db
      
  tbot:
    container_name: dbot
    build: 
      context: .
    command: python main.py
    volumes:
      - .:/src
    ports:
      - 8201:8201
    depends_on:
      - deleteme_db
      - web
    restart: always
    networks: 
      - deleteme_botnet

networks: 
  deleteme_botnet:
      driver: bridge

